apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cart-config
    envs:
    - ./common/common.env
    - ./cart/cart.env

generatorOptions:
  disableNameSuffixHash: true
