apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cart-config
    envs:
      - cart/cart.env
      - common/common.env

generatorOptions:
  disableNameSuffixHash: true
